# Generated by Django 3.1.13 on 2021-07-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(help_text='Enter email personas addresses to send log data', max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SenderEmailConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email_address', models.EmailField(help_text='Enter sender email address to send log data from', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='XMSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xis_metadata_api', models.CharField(default='http://localhost:8080/api/metadata/', help_text='Enter the XIS api endpoint to query metadata', max_length=200)),
                ('xis_catalogs_api', models.CharField(default='http://localhost:8080/api/catalogs/', help_text='Enter the XIS api endpoint to get catalogs', max_length=200)),
            ],
        ),
    ]
