# Generated by Django 3.1.8 on 2021-04-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xis_host', models.CharField(help_text='Enter the host url for the XIS (Experience Indexing Service)', max_length=200)),
            ],
        ),
    ]
