# Generated by Django 3.1.13 on 2021-07-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xmsconfiguration',
            name='xis_host',
        ),
        migrations.AddField(
            model_name='xmsconfiguration',
            name='target_xis_metadata_api',
            field=models.CharField(default='http://localhost:8080/api/metadata/', help_text='Enter the XIS api endpoint to query metadata', max_length=200),
        ),
        migrations.AddField(
            model_name='xmsconfiguration',
            name='xis_catalogs_api',
            field=models.CharField(default='http://localhost:8080/api/catalogs/', help_text='Enter the XIS api endpoint to get catalogs', max_length=200),
        ),
    ]
