# Generated by Django 3.1.14 on 2022-02-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220216_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xmsconfiguration',
            options={'verbose_name': 'XMS Connection Configuration'},
        ),
    ]
