# Generated by Django 3.1.14 on 2022-02-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220217_1125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='XMSConfiguration',
        ),
    ]
