# Generated by Django 3.1.14 on 2022-02-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XMSConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_xis_metadata_host', models.CharField(default='http://localhost:8080/api/metadata/', help_text='Enter the XIS host to query metadata', max_length=200)),
                ('target_xis_catalogs_host', models.CharField(default='http://localhost:8080/api/catalogs/', help_text='Enter the XIS host to get available catalogs', max_length=200)),
            ],
            options={
                'verbose_name': 'XMS Connection',
            },
        ),
    ]
