# Generated by Django 3.1.14 on 2023-07-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_xmsconfigurations_xis_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmsconfigurations',
            name='xis_api_key',
            field=models.CharField(help_text='Enter the XIS API Key', max_length=128),
        ),
    ]
